INSERT INTO users (f_name, l_name, username, email, password) VALUES ('John','doe', 'johndoe','johndoe@mail.com',crypt('1234', gen_salt('bf')));
INSERT INTO users (f_name, l_name, username, email, password) VALUES ('Janet','doe', 'janetdoe','johndoe@mail.com',crypt('1234', gen_salt('bf')));
INSERT INTO users (f_name, l_name, username, email, password) VALUES ('Robert','doe', 'robertdoe','johndoe@mail.com',crypt('1234', gen_salt('bf')));
INSERT INTO users (f_name, l_name, username, email, password) VALUES ('Bethany','doe', 'bethanydoe','johndoe@mail.com',crypt('1234', gen_salt('bf')));
INSERT INTO users (f_name, l_name, username, email, password) VALUES ('Rich','doe', 'richdoe','johndoe@mail.com',crypt('1234', gen_salt('bf')));
INSERT INTO users (f_name, l_name, username, email, password) VALUES ('Amy','doe', 'amydoe','johndoe@mail.com',crypt('1234', gen_salt('bf')));
INSERT INTO users (f_name, l_name, username, email, password) VALUES ('Patrick','doe', 'patrickdoe','johndoe@mail.com',crypt('1234', gen_salt('bf')));
INSERT INTO users (f_name, l_name, username, email, password) VALUES ('Rachel','doe', 'racheldoe','johndoe@mail.com',crypt('1234', gen_salt('bf')));
INSERT INTO users (f_name, l_name, username, email, password) VALUES ('Mike','doe', 'mikedoe','johndoe@mail.com',crypt('1234', gen_salt('bf')));
INSERT INTO users (f_name, l_name, username, email, password) VALUES ('Julie','doe', 'juliedoe','johndoe@mail.com',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Margarette', 'Overall', 'moverall0', 'moverall0@webmd.com',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Elle', 'Gilcrist', 'egilcrist1', 'egilcrist1@fotki.com',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Afton', 'Gosden', 'agosden2', 'agosden2@forbes.com',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Cazzie', 'Booth-Jarvis', 'cboothjarvis3', 'cboothjarvis3@icio.us',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Arthur', 'Burles', 'aburles4', 'aburles4@sina.com.cn',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Lilllie', 'Broadbere', 'lbroadbere5', 'lbroadbere5@ft.com',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Germain', 'Lenthall', 'glenthall6', 'glenthall6@blinklist.com',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Keri', 'Titherington', 'ktitherington7', 'ktitherington7@amazon.co.uk',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Ronald', 'Kikke', 'rkikke8', 'ckikke8@gravatar.com',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Brandi', 'Quilliam', 'bquilliam9', 'bquilliam9@sakura.ne.jp',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Ernst', 'Sigge', 'esiggea', 'esiggea@goo.ne.jp',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Pebrook', 'Veighey', 'pveigheyb', 'pveigheyb@dell.com',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Vitoria', 'Shovelbottom', 'vshovelbottomc', 'vshovelbottomc@theguardian.com',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('David', 'Prall', 'dpralld', 'dpralld@microsoft.com',crypt('1234', gen_salt('bf')));
insert into users (f_name, l_name, username, email, password) values ('Zora', 'Blennerhassett', 'zblennerhassette', 'zblennerhassette@globo.com',crypt('1234', gen_salt('bf')));

INSERT INTO info (user_id, personality, bio, gender, interest, pic) VALUES ('1', 'hungry, hopeless, tired', 'Looking for my soulmate out there.', 'Men', 'Women', 'profile_pics/johndoe.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=1;
INSERT INTO info (user_id, personality, bio, gender, interest, pic) VALUES ('2', 'hungry, hopeless, tired', 'Looking for my soulmate out there.', 'Women', 'Men', 'profile_pics/janetdoe.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=2;
INSERT INTO info (user_id, personality, bio, gender, interest, pic) VALUES ('3', 'hungry, hopeless, tired', 'Looking for my soulmate out there.', 'Men', 'Women', 'profile_pics/robertdoe.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=3;
INSERT INTO info (user_id, personality, bio, gender, interest, pic) VALUES ('4', 'hungry, hopeless, tired', 'Looking for my soulmate out there.', 'Women', 'Men', 'profile_pics/bethanydoe.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=4;
INSERT INTO info (user_id, personality, bio, gender, interest, pic) VALUES ('5', 'hungry, hopeless, tired', 'Looking for my soulmate out there.', 'Men', 'Women', 'profile_pics/richdoe.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=5;
INSERT INTO info (user_id, personality, bio, gender, interest, pic) VALUES ('6', 'hungry, hopeless, tired', 'Looking for my soulmate out there.', 'Women', 'Men', 'profile_pics/amydoe.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=6;
INSERT INTO info (user_id, personality, bio, gender, interest, pic) VALUES ('7', 'hungry, hopeless, tired', 'Looking for my soulmate out there.', 'Men', 'Men', 'profile_pics/patrickdoe.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=7;
INSERT INTO info (user_id, personality, bio, gender, interest, pic) VALUES ('8', 'hungry, hopeless, tired', 'Looking for my soulmate out there.', 'Women', 'Women', 'profile_pics/racheldoe.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=8;
INSERT INTO info (user_id, personality, bio, gender, interest, pic) VALUES ('9', 'hungry, hopeless, tired', 'Looking for my soulmate out there.', 'Men', 'Men', 'profile_pics/mikedoe.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=9;
INSERT INTO info (user_id, personality, bio, gender, interest, pic) VALUES ('10', 'hungry, hopeless, tired', 'Looking for my soulmate out there.', 'Women', 'Women', 'profile_pics/juliedoe.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=10;
insert into info (user_id, personality, bio, gender, interest, pic) values (11, 'funny', 'I am a lifelong learner who is always seeking new knowledge and experiences.', 'Women', 'Men', 'profile_pics/user11.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=11;
insert into info (user_id, personality, bio, gender, interest, pic) values (12, 'outgoing', 'I am a passionate individual with a love for technology and innovation.', 'Women', 'Women', 'profile_pics/user12.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=12;
insert into info (user_id, personality, bio, gender, interest, pic) values (13, 'intelligent', 'I am a creative artist who finds inspiration in nature and the beauty of the world.', 'Men', 'Men', 'profile_pics/user13.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=13;
insert into info (user_id, personality, bio, gender, interest, pic) values (14, 'charismatic', 'I am a creative artist who finds inspiration in nature and the beauty of the world.', 'Women', 'Women', 'profile_pics/user14.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=14;
insert into info (user_id, personality, bio, gender, interest, pic) values (15, 'funny', 'I am a lifelong learner who is always seeking new knowledge and experiences.', 'Men', 'Women', 'profile_pics/user15.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=15;
insert into info (user_id, personality, bio, gender, interest, pic) values (16, 'charismatic', 'I have a background in finance and enjoy analyzing market trends.', 'Women', 'Men', 'profile_pics/user16.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=16;
insert into info (user_id, personality, bio, gender, interest, pic) values (17, 'compassionate', 'I am a dedicated athlete who strives for excellence in every game.', 'Men', 'Men', 'profile_pics/user17.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=17;
insert into info (user_id, personality, bio, gender, interest, pic) values (18, 'reliable', 'I am a creative artist who finds inspiration in nature and the beauty of the world.', 'Women', 'Women', 'profile_pics/user18.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=18;
insert into info (user_id, personality, bio, gender, interest, pic) values (19, 'honest', 'I am a lifelong learner who is always seeking new knowledge and experiences.', 'Men', 'Women', 'profile_pics/user19.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=19;
insert into info (user_id, personality, bio, gender, interest, pic) values (20, 'honest', 'I am a passionate individual with a love for technology and innovation.', 'Women', 'Women', 'profile_pics/user20.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=20;
insert into info (user_id, personality, bio, gender, interest, pic) values (21, 'funny', 'I have a background in finance and enjoy analyzing market trends.', 'Men', 'Women', 'profile_pics/user21.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=21;
insert into info (user_id, personality, bio, gender, interest, pic) values (22, 'honest', 'I am a lifelong learner who is always seeking new knowledge and experiences.', 'Men', 'Men', 'profile_pics/user22.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=22;
insert into info (user_id, personality, bio, gender, interest, pic) values (23, 'compassionate', 'I have a background in finance and enjoy analyzing market trends.', 'Women', 'Women', 'profile_pics/user23.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=23;
insert into info (user_id, personality, bio, gender, interest, pic) values (24, 'trustworthy', 'I am a creative artist who finds inspiration in nature and the beauty of the world.', 'Men', 'Women', 'profile_pics/user24.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=24;
insert into info (user_id, personality, bio, gender, interest, pic) values (25, 'optimistic', 'I am a lifelong learner who is always seeking new knowledge and experiences.', 'Women', 'Men', 'profile_pics/user25.jpg');
insert into matches(user1_id, user2_id) Select users.id, info.id from users join info on users.id!=info.user_id and users.id=25;


-- INSERT INTO messages (match_id, user_id, message) VALUES ('8', '5', 'Hey whats up');
-- INSERT INTO messages (match_id, user_id, message) VALUES ('8', '2', 'well howdy!');